import type { Course } from '../types'

export const course: Course = {
  title: 'Common Vue.js Mistakes and How to Avoid Them',
  lessons: [
    { id: 1, key: '', subject: 'Course Intro', url: '', slug: '' },
    {
      id: 2,
      key: 'Key on v-for',
      subject: 'Omitting the Key Directive on v-for',
      url: 'https://vueschool.io/lessons/omitting-the-key-directive-on-v-for',
      slug: 'key-on-v-for',
    },
    {
      id: 3,
      key: '',
      subject: 'Prop Drilling',
      url: 'https://vueschool.io/lessons/prop-drilling',
      slug: 'provide-inject-state-management',
    },
    {
      id: 4,
      key: '',
      subject: 'Watching Arrays the Wrong Way',
      url: 'https://vueschool.io/lessons/watching-arrays-the-wrong-way',
      slug: '',
    },
    {
      id: 5,
      key: '',
      subject: 'Replacing Reactive State the Wrong Way',
      url: 'https://vueschool.io/lessons/replacing-reactive-state-the-wrong-way',
      slug: '',
    },
    {
      id: 6,
      key: '',
      subject: 'Unintentionally Mutating Props',
      url: 'https://vueschool.io/lessons/unintentionally-mutating-props',
      slug: '',
    },
    {
      id: 7,
      key: '',
      subject: 'Forgetting to Clean Up Your Manual Event Listeners',
      url: 'https://vueschool.io/lessons/forgetting-to-clean-up-your-manual-event-listeners',
      slug: '',
    },
    {
      id: 8,
      key: '',
      subject: 'Expecting Changes to Non-Reactive Dependencies to Trigger Updates',
      url: 'https://vueschool.io/lessons/expecting-changes-to-non-reactive-dependencies-to-trigger-updates',
      slug: '',
    },
    {
      id: 9,
      key: '',
      subject: 'Not Considering TypeScript',
      url: 'https://vueschool.io/lessons/not-considering-typescript',
      slug: '',
    },
    {
      id: 10,
      key: '',
      subject: 'Destructuring Reactive Data',
      url: 'https://vueschool.io/lessons/destructuring-reactive-data',
      slug: '',
    },
    {
      id: 11,
      key: '',
      subject: 'Calling Composables in the Wrong Place',
      url: 'https://vueschool.io/lessons/calling-composables-in-the-wrong-place',
      slug: '',
    },
    {
      id: 12,
      key: '',
      subject: 'Using v-html with User Provided Data',
      url: 'https://vueschool.io/lessons/using-v-html-with-user-provided-data',
      slug: '',
    },
    {
      id: 13,
      key: '',
      subject: 'Unnecessary Manual DOM Manipulation',
      url: 'https://vueschool.io/lessons/unnecessary-manual-dom-manipulation',
      slug: '',
    },
    {
      id: 14,
      key: '',
      subject: 'Course Conclusion',
      url: 'https://vueschool.io/lessons/common-vue-js-mistakes-course-conclusion',
      slug: '',
    },
  ],
}
